version: '3.8'

services:
  negotiation-agent:
    container_name: negotiation-agent
    image: negotiation-agent:latest
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./src:/app/src
    network_mode: host
    restart: unless-stopped